version: '3.8'

services:
  postgres:
    profiles:
      - posgres
    image: postgres:latest
    container_name: planriean_db
    hostname: planriean_db
    domainname: dev
    environment:
      POSTGRES_DB: planriean_uat
      POSTGRES_USER: myplan
      POSTGRES_PASSWORD: My7Ho!c3
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planriean
  certbot:
    profiles:
      - certbot
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --deploy-hook \"nginx -s reload\"; sleep 12h; done;'"
    networks:
      - planriean
  nginx:
    profiles:
      - nginx
    image: nginx_custom:latest
    restart: unless-stopped
    container_name: nginx-proxy
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - planriean
    command: ["nginx", "-g", "daemon off;"]

volumes:
  postgres_data:
    external: true

networks:
  planriean:
