version: '3.8'

services:
  postgres:
    profiles:
      - posgres
    image: postgres:latest
    container_name: planriean-db
    hostname: planriean-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: planriean_master
      POSTGRES_USER: planriean_user
      POSTGRES_PASSWORD: P1anS4O0Om92lan4!3aN
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - planriean
  nginx:
    profiles:
      - nginx
    image: nginx_custom:latest
    restart: unless-stopped
    container_name: planriean-nginx
    volumes:
      - ./certs:/etc/letsencrypt/live
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_planriean
    command: ["nginx", "-g", "daemon off;"]

volumes:
  postgres_data:
    external: true
networks:
  nginx_planriean:
    external: true