version: '3.8'

services:
  postgres:
    profiles:
      - posgres
    image: postgres:latest
    container_name: planriean_db_uat
    environment:
      POSTGRES_DB: planriean_uat
      POSTGRES_USER: myplan
      POSTGRES_PASSWORD: My7Ho!c3
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planriean
  nginx:
    profiles:
      - nginx
    image: nginx_custom:latest
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: "*.lvh.me"
    networks:
      - planriean
    volumes_from:
      - vnmsuapi-1
      - vnmsuapi-2

volumes:
  postgres_data:
    external: true

networks:
  planriean:
