import GoogleAnalytics from '@/GoogleAnalytics'
import type { Metadata } from 'next'
import { IBM_Plex_Sans_Thai } from 'next/font/google'

const font = IBM_Plex_Sans_Thai({ 
  weight: ["300", "500", "600"],
  subsets: ['latin', 'thai']
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={font.className}>
        {/* <GoogleAnalytics /> */}
      {children}
    </div>
  )
}
